const express = require("express");
const cors = require("cors");
const app = express();
const bodyParser = require("body-parser");
const serverless = require("serverless-http");
const app_ts = require("../app.ts");
app.use(bodyParser.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use(cors());
app.use("/.netlify/functions/api", app_ts);
module.exports.handler = serverless(app);
