[build]
  publish = "public"
  functions = "functions"
  command = "npm run build:functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[functions]
  node_bundle = true
  external_node_modules = ["express"]
